jobs:
  build:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: yarn
            - run: yarn build

version: 2.1
orbs:
  node: circleci/node@2.0.3
  heroku: circleci/heroku@1.0.1

workflows:
  heroku_deploy:
    jobs:
      - build
      - heroku/deploy-via-git:
        requires:
          - yarn
          - build
        filters:
          branches:
            only: master
